name: Python Tests

on: [push]

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: pip install tox
    - name: Validate formatting
      run: tox -e format

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        tox_env:
            - py311-django42
            - py311-django52
            - py312-django42
            - py312-django52
            - py313-django42
            - py313-django52
        include:
          - python-version: 3.11
            tox_env: py311-django42
          - python-version: 3.11
            tox_env: py311-django52
          - python-version: 3.12
            tox_env: py312-django42
          - python-version: 3.12
            tox_env: py312-django52
          - python-version: 3.13
            tox_env: py313-django42
          - python-version: 3.13
            tox_env: py313-django52

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox -e ${{ matrix.tox_env }}
    - name: Prepare artifacts
      run: mkdir .coverage-data && mv .coverage.* .coverage-data/
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-data-${{ matrix.tox_env }}
        include-hidden-files: true
        path: .coverage-data/

  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - uses: actions/download-artifact@v4
      with:
        pattern: coverage-data-*
        merge-multiple: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions coverage[toml]
    - name: Prepare Coverage report
      run: tox -e coverage-report
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
